# Generated by Django 3.2.5 on 2021-08-12 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0018_auto_20210812_0752'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectDetails',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('plastic', models.PositiveIntegerField(verbose_name='Plastic')),
                ('papper', models.PositiveIntegerField(verbose_name='Papper')),
                ('metal', models.PositiveIntegerField(verbose_name='Metal')),
                ('food_waste', models.PositiveIntegerField(verbose_name='FoodWaste')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
