# Generated by Django 3.2.5 on 2021-08-12 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectdetails',
            name='address',
        ),
    ]
