# Generated by Django 3.2.5 on 2021-08-13 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_remove_collectdetails_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CollectDetails',
        ),
    ]
