# Generated by Django 3.2.4 on 2021-07-16 08:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('house_name', models.CharField(max_length=250, verbose_name='Name')),
                ('address_line_1', models.CharField(max_length=250, verbose_name='Address Line 1')),
                ('address_line_2', models.CharField(blank=True, help_text='Optional', max_length=250, null=True, verbose_name='Address Line 2')),
                ('pin', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999)], verbose_name='PIN CODE')),
                ('phone_number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)], verbose_name='Mobile Number')),
                ('District', models.CharField(choices=[('Ernakulam', 'Ernakulam'), ('Kottayam', 'Kottayam'), ('Idukki', 'Idukki')], max_length=25, verbose_name='Disctrict')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
