# Generated by Django 3.2.4 on 2021-07-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='house_name',
            field=models.CharField(max_length=250, verbose_name='hose Name'),
        ),
    ]
