# Generated by Django 3.2.4 on 2021-07-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
