# Generated by Django 3.2.4 on 2021-07-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_cart_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(default='pending...', max_length=20, verbose_name='status'),
        ),
    ]
