# Generated by Django 3.2.5 on 2021-07-21 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_rename_district_booking_sistrict'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
