# Generated by Django 3.2.5 on 2021-07-21 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_booking_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='sistrict',
            new_name='district',
        ),
    ]
