# Generated by Django 3.2.5 on 2021-07-21 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_rename_sistrict_booking_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
        migrations.AddField(
            model_name='booking',
            name='has_completed',
            field=models.BooleanField(default=False),
        ),
    ]
