# Generated by Django 3.2.5 on 2021-08-12 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20210812_0752'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
