# Generated by Django 3.2.5 on 2021-08-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('Home', 'Home'), ('Office', 'Office')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
