# Generated by Django 3.2.5 on 2021-08-20 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_address_address_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='has_completed',
        ),
    ]
