# Generated by Django 3.2.5 on 2021-08-20 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_remove_address_has_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='has_completed',
            field=models.BooleanField(default=False, max_length=100),
        ),
    ]
